DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  surname VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(40) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  created timestamp
);

ALTER TABLE COMMENT
    ADD CONSTRAINT comment_user_id
    FOREIGN KEY (user_id) REFERENCES comment(id);